#!/bin/bash

if [ -z $1 ]; then
    echo -e "Usage: \"arxivPDF xxxx.xxxx\" or \"arxivPDF xxxx.xxxx [tag]\"" 
    echo -e "Papers will save to $HOME/papers/arxiv or $HOME/papers/[tag]." 
else
    if [ ! -d $HOME/papers ]; then
        mkdir -p $HOME/papers/arxiv
    fi
    FOUND=`find $HOME/papers -type f -name $1.pdf` 
    FOUND=`echo $FOUND | wc -c` 
    if [ $FOUND == 1 ] && [ -z $2 ]; then
        if [ ! -f $HOME/papers/arxiv/$1.pdf ]; then
            curl https://arxiv.org/pdf/$1.pdf > $HOME/papers/arxiv/$1.pdf
        fi
    elif [ $FOUND == 1 ]; then
        if [ ! -d $HOME/papers/$2 ]; then
            mkdir $HOME/papers/$2
        fi
        curl https://arxiv.org/pdf/$1.pdf > $HOME/papers/$2/$1.pdf
    else
        if [ ! -d $HOME/papers/$2 ]; then
            mkdir $HOME/papers/$2
        fi
        find $HOME/papers -type f -name $1.pdf -exec mv {}  $HOME/papers/$2/$1.pdf \; 
    fi
    READABLE=`find $HOME/papers -type f -name $1.pdf -exec zathura {} \; `
    if [ "$READABLE" != "error: could not open document" ]; then
        echo "CANTOT read"
        find $HOME/papers -type f -name $1.pdf -exec rm -i {} \;
    fi
fi
